Initial GRUB bootloader support

diff --git a/conf/installer/main b/conf/installer/main
--- a/conf/installer/main
+++ b/conf/installer/main
@@ -7,11 +7,14 @@
 ## This is free software, and you are welcome to redistribute it
 ## under certain conditions; see COPYING for details.
 
+INSTALLER_DIR="$(dirname $0)"
 SOURCE_DIR=/source
 SOURCE_IMAGE_FILE="$SOURCE_DIR/filesystem.sqfs"
 SOURCE_IMAGE_MD5SUM_FILE="$SOURCE_DIR/filesystem.md5sum"
 TARGET_DIR=/target
 LOG_FILE=/run/installer.log
+
+source "$INSTALLER_DIR/config"
 
 USER_NAME=loongson
 USER_PASS=loongson
@@ -21,10 +24,15 @@ OS_NAME=Loongbian
 
 ROOTFS_TYPE=ext4
 ROOTFS_MK_OPTS=
+SWAP_SIZE=512M
+
+# BOOT_FS_* options are applicable only if bootloader is PMON
 BOOT_FS_TYPE=ext3
 BOOT_FS_MK_OPTS=
 BOOT_FS_SIZE=256M
-SWAP_SIZE=512M
+
+# ESP_* options are applicable only if bootloader is GRUB
+ESP_SIZE=64M
 
 WT_TITLE="$OS_NAME Installer"
 WT_HEIGHT=20
@@ -120,16 +128,25 @@ choose_target() {
     if [ $? -eq 1 ]; then
       continue
     fi
-    BOOT_FS_TARGET=${TARGET_DISK}1
-    ROOTFS_TARGET=${TARGET_DISK}2
-    SWAP_TARGET=${TARGET_DISK}3
     return 0
   done
 }
 
-
-
 partition_and_format_target() {
+  if [ "$CONFIG_BOOTLOADER" = "pmon" ]; then
+    partition_and_format_target_pmon
+  elif [ "$CONFIG_BOOTLOADER" = "grub" ]; then
+    partition_and_format_target_grub
+  else
+    wt_msg_error "BUG: Unsupported bootloader type $CONFIG_BOOTLOADER."
+    return 1
+  fi
+}
+
+partition_and_format_target_pmon() {
+  BOOT_FS_TARGET="${TARGET_DISK}1"
+  ROOTFS_TARGET="${TARGET_DISK}2"
+  SWAP_TARGET="${TARGET_DISK}3"
   {
     wt_gauge_update_status 20 "Partitioning $TARGET_DISK..."
     logged parted -s -- "$TARGET_DISK" \
@@ -147,9 +164,45 @@ partition_and_format_target() {
     logged "mkfs.$ROOTFS_TYPE" $ROOTFS_MK_OPTS "$ROOTFS_TARGET"  || return 5
     logged mount -t "$ROOTFS_TYPE" "$ROOTFS_TARGET" "$TARGET_DIR" || return 6
     wt_gauge_update_status 60 "Creating boot filesystem on $BOOT_FS_TARGET..."
-    logged "mkfs.$BOOT_FS_TYPE" "$BOOT_FS_MK_OPTS" "$BOOT_FS_TARGET" || return 3
+    logged "mkfs.$BOOT_FS_TYPE" $BOOT_FS_MK_OPTS "$BOOT_FS_TARGET" || return 3
     mkdir -p "$TARGET_DIR/boot"
     logged mount -t "$BOOT_FS_TYPE" "$BOOT_FS_TARGET" "$TARGET_DIR/boot" || return 4
+    wt_gauge_update_status 80 "Creating swap on $SWAP_TARGET..."
+    logged mkswap "$SWAP_TARGET" || return 7
+  } | whiptail --gauge "Partitioning..." $WT_HEIGHT_SM $WT_WIDTH 0
+  RET=$?
+  if [ ! $RET -eq 0 ]; then
+    wt_msg_error "code $RET"
+    return 1
+  fi
+  return 0
+}
+
+partition_and_format_target_grub() {
+  ESP_TARGET="${TARGET_DISK}1"
+  ROOTFS_TARGET="${TARGET_DISK}2"
+  SWAP_TARGET="${TARGET_DISK}3"
+  {
+    wt_gauge_update_status 20 "Partitioning $TARGET_DISK..."
+    logged parted -s -- "$TARGET_DISK" \
+      mklabel gpt \
+      mkpart EFI fat32 2048s "$ESP_SIZE" \
+      mkpart rootfs ext4 "$ESP_SIZE" "-$SWAP_SIZE" \
+      mkpart swap linux-swap "-$SWAP_SIZE" -2048s \
+      set 1 boot on || return 1
+    partprobe "$TARGET_DISK"
+    sleep 1
+    if [ ! -b "$ESP_TARGET" ] || [ ! -b "$ROOTFS_TARGET" ] || [ ! -b "$SWAP_TARGET" ]; then
+      log "Could not find the target partitions."
+      return 2
+    fi
+    wt_gauge_update_status 40 "Creating root filesystem on $ROOTFS_TARGET..."
+    logged "mkfs.$ROOTFS_TYPE" $ROOTFS_MK_OPTS "$ROOTFS_TARGET"  || return 5
+    logged mount -t "$ROOTFS_TYPE" "$ROOTFS_TARGET" "$TARGET_DIR" || return 6
+    wt_gauge_update_status 60 "Creating boot filesystem on $ESP_TARGET..."
+    logged mkfs.vfat -F32 "$ESP_TARGET" || return 3
+    mkdir -p "$TARGET_DIR/boot/efi"
+    logged mount -t vfat "$ESP_TARGET" "$TARGET_DIR/boot/efi" || return 4
     wt_gauge_update_status 80 "Creating swap on $SWAP_TARGET..."
     logged mkswap "$SWAP_TARGET" || return 7
   } | whiptail --gauge "Partitioning..." $WT_HEIGHT_SM $WT_WIDTH 0
@@ -201,6 +254,17 @@ post_inst_add_user() {
 }
 
 post_inst_configure_boot() {
+  if [ "$CONFIG_BOOTLOADER" = "pmon" ]; then
+    post_inst_configure_boot_pmon
+  elif [ "$CONFIG_BOOTLOADER" = "grub" ]; then
+    post_inst_configure_boot_grub
+  else
+    wt_msg_error "BUG: Unsupported bootloader type $CONFIG_BOOTLOADER."
+    return 1
+  fi
+}
+
+post_inst_configure_boot_pmon() {
   log "Configuring /etc/fstab..."
   ROOTFS_UUID=$(lsblk -no UUID "$ROOTFS_TARGET")
   BOOT_FS_UUID=$(lsblk -no UUID "$BOOT_FS_TARGET")
@@ -225,6 +289,38 @@ post_inst_configure_boot() {
     fi
   else
     log 'Could not find pmon-update, skipping PMON configuration.'
+  fi
+  return 0
+}
+
+post_inst_configure_boot_grub() {
+  log "Configuring /etc/fstab..."
+  ROOTFS_UUID=$(lsblk -no UUID "$ROOTFS_TARGET")
+  ESP_UUID=$(lsblk -no UUID "$ESP_TARGET")
+  SWAP_UUID=$(lsblk -no UUID "$SWAP_TARGET")
+  if [ "$ROOTFS_UUID" = "" ] || [ "$ESP_UUID" = "" ] || [ "$SWAP_UUID" = "" ]; then
+    wt_msg_error "Unable to determine filesystem UUIDs."
+    return 1
+  fi
+  FSTAB_FILE="$TARGET_DIR/etc/fstab"
+  echo "# GENERATED BY SIMPLE INSTALLER" > "$FSTAB_FILE"
+  echo "UUID=$ROOTFS_UUID	/		$ROOTFS_TYPE	errors=remount-ro 0 1" >> "$FSTAB_FILE"
+  echo "UUID=$ESP_UUID		/boot/efi	vfat		umask=0077 0 1" >> "$FSTAB_FILE"
+  echo "UUID=$SWAP_UUID		none		swap		sw 0 0" >> "$FSTAB_FILE"
+
+  log "Configuring GRUB..."
+  logged mount -t proc /proc "$TARGET_DIR/proc"
+  logged mount --rbind /sys "$TARGET_DIR/sys"
+  logged mount --rbind /dev "$TARGET_DIR/dev"
+  logged chroot "$TARGET_DIR" grub-install --no-nvram --removable --target "$CONFIG_GRUB_TARGET" && \
+    logged chroot "$TARGET_DIR" update-grub
+  RET=$?
+  logged umount "$TARGET_DIR/proc"
+  logged umount "$TARGET_DIR/sys"
+  logged umount "$TARGET_DIR/dev"
+  if [ $RET -ne 0 ]; then
+    wt_msg_error "Failed to install GRUB."
+    return 1
   fi
   return 0
 }
@@ -268,7 +364,15 @@ umount_all() {
   fi
 
   if [ ! "$TARGET_DISK" = "" ]; then
-    umount "$TARGET_DIR/boot"
+    if [ -n "$ESP_TARGET" ]; then
+      umount "$ESP_TARGET"
+      ESP_TARGET=
+    fi
+
+    if [ -n "$BOOT_FS_TARGET" ]; then
+      umount "$BOOT_FS_TARGET"
+      BOOT_FS_TARGET=
+    fi
     umount "$TARGET_DIR"
     TARGET_DISK=
   fi
